### ISSUE TITLE
DESIGN

### ISSUE THREAD

**Issue by HokieGeek** [HokieGeek/snotify#5]
There are two core ideas that will drive this:
### Triggers

These kick of a notification
- Low battery level
- Caps Lock state
- Bluetooth state
### Notification channels

The notifications which will be instigated by a trigger
- OSD
- Email
- Pushbullet

**Comment by HokieGeek** [comment]
## Configuration file

``` yaml
system-notifier:
    triggers:
        trigger:
            id: 0
            name: Low battery level
            handler: lowbatt.sh
        trigger:
            id: 1
            name: Bluetooth connection state
            handler: bluetooth.sh
        trigger:
            id: 2
            name: Caps lock state
            handler: capslock.sh
    notifiers:
        notifier:
            id: 0
            name: OSD
            handler: osd_notifier.sh
        notifier:
            id: 1
            name: Pushbullet
            handler: pushbullet.sh
        notifier:
            id: 2
            name: Email
            handler: email.sh
        paths:
            0: [0, 1]
            1: [0]
            2: [0]
```

#### How about this instead?

``` yaml
hgnotifier:
    port: 9999
    color-bg: #000000
    color-fg: #FFFFFF
    triggers:
        capslock-state: [capslock-listener]
    notifiers:
        capslock-state: [capslock-osd.sh]
        bluetooth-state: [bluetooth-osd.sh]
        low-battery: [lowbattery-osd.sh, lowbattery-pb.sh]
```
